try {
  exit()
} catch e {
  println('exited')
}
