try {
}
catch e : ValueError {
  println(0)
}